### PR TITLE
Track 1.3.x branch

### PR DESCRIPTION
**Pull request by Andor**

### CODE REVIEW

**Comment by javacruft** [comment]
Hi

Thanks for the PR; I did a quick test having reviewed the travis build log and it looks like the Vault project have failed to add a tag to the release/1.3.x branch for the 1.3.0 release, so although your proposed change should work, its not right now.

**Comment by Andor** [comment]
@javacruft I'm not familiar with snapcrafters' build infrastructure, maybe you have some advice how to get working 1.3? Right now I see only version 1.1 in snap packages, not even 1.2.

**Comment by javacruft** [comment]
I was going to merge the commit associated with the v1.3.0 release into the release/1.3.x branch and proposed a PR but I've not signed the CLA and I'd need my employer to authorise that (which won't be a problem - just means I can't do it today!).

**Comment by javacruft** [comment]
I've pushed 1.3.x support to the master branch - needed a few other tweaks.

**Pull request closed without merging**
